/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())

    val multiplicar = new MultiplicarMatrices
    val m1 = multiplicar.matrizAlAzar(25, 25)
    val m2 = multiplicar.matrizAlAzar(25, 25)
    println("Matriz 1: " , m1)
    println("Matriz 2: " , m2)
    println("----------------------------------------------------------------")
    println("Matriz Resultante: " , multiplicar.multMatriz(m1, m2))
    
    println("----------------------------------------------------------------")
    
    val multiplicarParalelas = new MultiplicarMatricesParalelas
    val m1p = multiplicarParalelas.matrizAlAzar(25, 25)
    val m2p = multiplicarParalelas.matrizAlAzar(25, 25)
    println("Matriz 1: " , m1p)
    println("Matriz 2: " , m2p)
    println("----------------------------------------------------------------")
    println("Matriz Resultante: " , multiplicarParalelas.multMatriz(m1p, m2p))
  

   
  }

  def greeting(): String = "Hello, world!"
}
